### ISSUE TITLE
Unknown License

### ISSUE THREAD

**Issue by johnpaulett** [michaeljones/sphinx-to-github#2]
Thanks for putting this script together!

I was wondering what the License is on it (eg BSD, Apache, GPL, Public Domain, etc)?  I as because I would like to include the script in a project I host on github, so that all the developers can build the documentation, without having to download this script separately from their checkout of my project.

Thanks again!

**Comment by michaeljones** [comment]
Hey, good point, I'm a bit slack, and indeed ignorant, on the licence front. Very happy for you to include a copy... so BSD? If that works, I'll add the appropriate text when I can.

You might not want to grab it quite yet though, I think the new Python implementation goes a little overboard (renames all directories with an underscore in them, instead of just top level directories that start with an underscore.) I'm hoping to clean it up over the next couple of days.

**Comment by johnpaulett** [comment]
BSD would be perfect for me.  I think it would be appropriate because it gives people flexibility (people can include it in BSD and GPL'ed projects).  The only theoretical downside (depending on your point of view) is that people could distribute it in a closed source project.

Sounds good. Thanks for putting this code together!

**Comment by michaeljones** [comment]
All done, licence and rewrite, hope it works!

**Comment by johnpaulett** [comment]
Thanks for doing this!
